[settings]
animate = false
animation_duration = 0.3
animation_fps = 100.0
animation_easing = "ease_in_out"
default_disable = false
mouse_follows_focus = true
mouse_hides_on_focus = true
focus_follows_mouse = true
auto_focus_blacklist = []
run_on_start = [
    "sketchybar",
    "borders",
]
hot_reload = true

[settings.layout]
mode = "bsp"

[settings.layout.traditional]
equalize_nodes = true

[settings.layout.bsp]

[settings.layout.stack]
stack_offset = 40.0
default_orientation = "perpendicular"

[settings.layout.master_stack]
master_ratio = 0.6
master_count = 1
master_side = "left"
new_window_placement = "master"

[settings.layout.gaps.outer]
top = 10.0
left = 10.0
bottom = 10.0
right = 10.0

[settings.layout.gaps.inner]
horizontal = 5.0
vertical = 5.0

[settings.layout.gaps.per_display.8AE4D30C-B51D-40A1-87ED-FAF61D77977F.outer]
top = 40.0
left = 10.0
bottom = 10.0
right = 10.0

[settings.layout.gaps.per_display.0E93594D-FC6A-49DF-A0D5-558DEB6AB387.outer]
top = 40.0
left = 10.0
bottom = 10.0
right = 10.0

[settings.layout.gaps.per_display.27A5F0D2-899B-48C3-8F1D-EA10BDDC5078.outer]
top = 40.0
left = 10.0
bottom = 10.0
right = 10.0

[settings.layout.gaps.per_display.2A7643BD-CA23-45B9-A50C-975BF97DBCDB.outer]
top = 40.0
left = 10.0
bottom = 10.0
right = 10.0

[settings.layout.gaps.per_display.51EF7829-FE57-4CC5-90F7-81313F12EA76.outer]
top = 40.0
left = 10.0
bottom = 10.0
right = 10.0

[settings.layout.scrolling]
column_width_ratio = 0.7
min_column_width_ratio = 0.3
max_column_width_ratio = 0.9
alignment = "center"
focus_navigation_style = "niri"

[settings.layout.scrolling.gestures]
enabled = false
invert_horizontal = false
vertical_tolerance = 0.4
fingers = 3
distance_pct = 0.08
propagate_to_workspace_swipe = false
workspace_switch_threshold = 0.625

[settings.ui.menu_bar]
enabled = true
show_empty = false
mode = "all"
active_label = "index"
display_style = "layout"
layout_folder = "~/.config/rift/layouts"

[settings.ui.stack_line]
enabled = false
hover = "hover"
thickness = 20.0
horiz_placement = "top"
vert_placement = "left"
spacing = 1.0

[settings.ui.mission_control]
enabled = false
fade_enabled = false
fade_duration_ms = 180.0

[settings.gestures]
enabled = false
consume_dock_swipe = true
invert_horizontal_swipe = false
swipe_vertical_tolerance = 0.4
skip_empty = true
fingers = 3
distance_pct = 0.08
haptics_enabled = true
haptic_pattern = "level_change"

[settings.window_snapping]
drag_swap_fraction = 0.3

[keys]
"Alt + Slash" = "toggle_orientation"
"Alt + M" = "toggle_fullscreen"
"Alt + Shift + Space" = "toggle_window_floating"
"Alt + Tab" = "switch_to_last_workspace"
"Alt + Z" = "toggle_space_activated"
"Alt + Ctrl + Q" = "save_and_exit"
"Alt + Shift + D" = "debug"
"Alt + Ctrl + E" = "unjoin_windows"
"Alt + Comma" = "toggle_stack"
"Alt + Shift + Ctrl + Space" = "toggle_focus_floating"
"Alt + Shift + F" = "toggle_fullscreen_within_gaps"
"Alt + Ctrl + S" = "serialize"

[keys."Alt + Shift + ArrowUp"]
join_window = "up"

[keys."Alt + K"]
move_focus = "up"

[keys."Alt + H"]
move_focus = "left"

[keys."Alt + 9"]
switch_to_workspace = 9

[keys."Alt + 8"]
switch_to_workspace = 8

[keys."Alt + Shift + 7"]
move_window_to_workspace = 7

[keys."Alt + Shift + Minus"]
resize_window_shrink = "horizontal"

[keys."Alt + J"]
move_focus = "down"

[keys."Alt + Shift + 4"]
move_window_to_workspace = 4

[keys."Alt + 6"]
switch_to_workspace = 6

[keys."Alt + Shift + 2"]
move_window_to_workspace = 2

[keys."Alt + Shift + 6"]
move_window_to_workspace = 6

[keys."Alt + Shift + ArrowRight"]
join_window = "right"

[keys."Alt + Shift + J"]
move_node = "down"

[keys."Alt + 7"]
switch_to_workspace = 7

[keys."Alt + Shift + 1"]
move_window_to_workspace = 1

[keys."Alt + Shift + 9"]
move_window_to_workspace = 9

[keys."Alt + 5"]
switch_to_workspace = 5

[keys."Alt + Shift + Tab".move_window_to_display]
selector = "left"

[keys."Alt + 0"]
switch_to_workspace = 0

[keys."Alt + 1"]
switch_to_workspace = 1

[keys."Alt + 2"]
switch_to_workspace = 2

[keys."Alt + 3"]
switch_to_workspace = 3

[keys."Alt + Shift + 8"]
move_window_to_workspace = 8

[keys."Alt + Shift + 0"]
move_window_to_workspace = 0

[keys."Alt + Shift + ArrowDown"]
join_window = "down"

[keys."Alt + Shift + 5"]
move_window_to_workspace = 5

[keys."Alt + 4"]
switch_to_workspace = 4

[keys."Alt + Shift + H"]
move_node = "left"

[keys."Alt + Shift + K"]
move_node = "up"

[keys."Alt + Shift + L"]
move_node = "right"

[keys."Alt + Shift + Equal"]
resize_window_grow = "horizontal"

[keys."Alt + Shift + ArrowLeft"]
join_window = "left"

[keys."Alt + L"]
move_focus = "right"

[keys."Alt + T"]
exec = [
    "/bin/bash",
    "-c",
    'open -a "WezTerm" -n',
]

[keys."Alt + Shift + 3"]
move_window_to_workspace = 3

[virtual_workspaces]
enabled = true
default_workspace_count = 10
auto_assign_windows = true
preserve_focus_per_workspace = true
workspace_auto_back_and_forth = false
prevent_wrapping = false
workspace_names = [
    "space.0",
    "space.1",
    "space.2",
    "space.3",
    "space.4",
    "space.5",
    "space.6",
    "space.7",
    "space.8",
    "space.9",
]
default_workspace = 1
reapply_app_rules_on_title_change = false
workspace_rules = []

[[virtual_workspaces.app_rules]]
app_id = "com.github.wez.wezterm"
workspace = 1
floating = false
focus = false
manage = true

[[virtual_workspaces.app_rules]]
app_id = "app.glide-browser.glide"
workspace = 2
floating = false
focus = false
manage = true

[[virtual_workspaces.app_rules]]
app_id = "com.microsoft.Outlook"
workspace = 3
floating = false
focus = false
manage = true

[[virtual_workspaces.app_rules]]
app_id = "com.cisco.Jabber"
workspace = 4
floating = false
focus = false
manage = true

[[virtual_workspaces.app_rules]]
app_id = "com.cisco.secureclient.gui"
floating = true
focus = true
manage = true

[modifier_combinations]
